apiVersion: apps/v1
kind: Deployment
metadata:
  name: vecnehladny-premises-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /vecnehladny-openapi
            - name: BASE_URL
              value: /vecnehladny-openapi-ui